#!/bin/bash
# based on answer here: https://stackoverflow.com/questions/31057527

# The formatter to use
formatter=`which vsg`

# Check availability of the formatter
if [ -z "$formatter" ]
then
  1>&2 echo "$formatter not found. Pre-commit formatting will not be done."
  exit 0
fi

# Format staged files
git diff --cached --name-only --diff-filter=ACMR | grep ".*.vhd$" | while read file; do
  echo "Formatting $file"
  $formatter --fix -f $file
  git add $file
done